#!/usr/bin/env bash

set -e

# source $SNAP/actions/common/utils.sh

NAMESPACE_GITLAB_RUNNER="gitlab-runner"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"
KUBECTL_DELETE_ARGS="--wait=true --timeout=180s --ignore-not-found=true"

PURGE=false
# get the options
while getopts ":p" flag; do
  case "${flag}" in
          p) PURGE=true
             ;;
          *) echo "Usage: microk8s disable gitlab-runner [-p]"
             echo ""
             echo "WARNING: Final deletion of \"$NAMESPACE_GITLAB_RUNNER\" namespace must be enforced by: \"microk8s disable argocd -p\""
             echo ""
             echo "Purge only when sure, that \"$NAMESPACE_GITLAB_RUNNER\" namespace is not hosting any other services from Argo stack."
             echo ""
             exit 0
             ;;
  esac
done

echo "Disabling GitLab Runner"

$HELM delete gitlab-runner -n $NAMESPACE_GITLAB_RUNNER



if $PURGE; then
    echo "Final \"$NAMESPACE_GITLAB_RUNNER\" namespace deletion"
    $KUBECTL delete $KUBECTL_DELETE_ARGS namespace "$NAMESPACE_GITLAB_RUNNER" > /dev/null 2>&1 || true
else
    echo ""
    echo "WARNING: Final deletion of \"$NAMESPACE_GITLAB_RUNNER\" namespace must be enforced by: \"microk8s disable gitlab-runner -p\""
    echo ""
    echo "Purge only when sure, that \"$NAMESPACE_GITLAB_RUNNER\" namespace is not hosting any other services from Argo stack."
    echo ""
fi

echo "GitLab disabled"
