#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_GITLAB_RUNNER="gitlab-runner"

GITLAB_RUNNER_HELM_VERSION="0.60.0"
"$SNAP/microk8s-enable.wrapper" helm3

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

VALUES=""

# get the options
while getopts ":v:f:h:" flag; do
  case "${flag}" in
          v) GITLAB_RUNNER_HELM_VERSION=${OPTARG}
             ;;
          f) VALUES=${OPTARG}
             ;;
          *) echo "Usage: microk8s enable gitlab-runner"
             echo ""
             echo "With overwriting default values: microk8s enable gitlab-runner -f values.yaml"
             echo ""
             echo "See https://charts.gitlab.io for more information about the values"
             exit 0
             ;;
  esac
done

echo "Installing GitLab Runner (Helm v${GITLAB_RUNNER_HELM_VERSION})"

if [ -n "$VALUES" ]; then
    echo "Using values file: $VALUES"
fi


# make sure the "gitlab-runner" namespace exists
$KUBECTL create namespace "$NAMESPACE_GITLAB_RUNNER" > /dev/null 2>&1 || true

# add the GitLab Runner chart repository
$HELM repo add gitlab https://charts.gitlab.io
# install the helm chart
if [ -z "$VALUES" ]
then
    $HELM upgrade -i gitlab gitlab/gitlab-runner \
      --version $GITLAB_RUNNER_HELM_VERSION \
      --namespace "$NAMESPACE_GITLAB_RUNNER"
else
    $HELM upgrade -i gitlab gitlab/gitlab-runner \
      --version $GITLAB_RUNNER_HELM_VERSION \
      --namespace "$NAMESPACE_GITLAB_RUNNER" \
      -f $VALUES
fi

echo "GitLab Runner is installed"
